services:
    db:
        image: "mysql:latest"
        environment:
            MYSQL_ROOT_PASSWORD: password
        ports:
            - "3306:3306"

    phpMyAdmin:
        image: 'phpmyadmin:latest'
        environment:
            PMA_ARBITRATY: 1
        ports:
            - "8080:80"
